### ISSUE TITLE
Missing constructor for IllegalCalendarFieldValueException?

### ISSUE THREAD

**Issue by dobesv** [soc/scala-datetime#2]
For example when I try to compile the current head of 'master', I get:

[info] Compiling 115 Scala sources to C:\Users\dobes\git\scala-datetime\target\scala-2.9.0.1\classes...
[error] C:\Users\dobes\git\scala-datetime\src\main\scala\scalax\time\calendar\AmPmOfDay.scala:94: overloaded method constructor IllegalCalendarFieldValueException with alternatives:
[error]   (fieldRule: scalax.time.calendar.DateTimeRule,actual: Long)scalax.time.calendar.IllegalCalendarFieldValueException <and>
[error]   (message: String,rule: scalax.time.calendar.DateTimeRule)scalax.time.calendar.IllegalCalendarFieldValueException
[error]  cannot be applied to (scalax.time.calendar.DateTimeRule, Int, Int, Int)
[error]       case _ => throw new IllegalCalendarFieldValueException(AmPmOfDayRule, amPmOfDay, 0, 1)
[error]                       ^

**Comment by soc** [comment]
Superseded by https://github.com/soc/threetenbp.
