### ISSUE TITLE
Port to Scala 2.11 and ScalaJS

### ISSUE THREAD

**Issue by antonkulaga** [soc/scala-datetime#3]
At the moment there is no datetime library that works both for ScalaJS and Scala and thus can be used in shared scala/scalajs code and shared libraries. Scala wrappers around Yoda do not fit to this purpose as they (due to Java part) do not compile to ScalaJS. 
I have not found any native scala datetime libs except for this one. I have no knowledge about differences between 2.9 and 2.11 (I think they are huge) so I failed to fork/port it myself =(

**Comment by soc** [comment]
https://github.com/soc/threetenbp :-)
